feat!: Separate gRPC and HTTP clients (#73)
* Start from scratch
* Create project skeleton
* Implement serverInfo
* Update dependencies
* Remove boilerplate script
* Set up tests
* Set up CI
* Allow TLS and mTLS for gRPC connections
* Test Unix sockets on Linux
* Switch to ts-proto
* Remove openapi-typescript
* Implement checkResources
* Add CheckResourcesResponse#findResult helper function
* Add CheckResourcesResult#isAllowed helper function
* Add CheckResourcesResponse#isAllowed helper function
* Add CheckResourcesResult#allAllowed helper function
* Add CheckResourcesResponse#allAllowed helper function
* Add CheckResourcesResult#allowedActions helper function
* Add CheckResourcesResponse#allowedActions helper function
* Implement checkResource
* Implement isAllowed
* Add onValidationError option
* Implement planResources
* Update dependencies
* Set user agent
* Handle errors
* Use stricter compiler options
* Regenerate protobuf code
* Add option to connect to hosted demo PDP with playground instance
* Add documentation
* Handle `-i` differences between GNU and BSD `sed`
* Handle normalized filter expressions
* Add "Get help" section to READMEs
* Publish sourcemaps and TypeScript sources for easier debugging

Signed-off-by: Andrew Haines <haines@cerbos.dev>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,17 +1,20 @@
 name: CI
 
 on:
-  - pull_request
+  pull_request:
+    branches:
+      - main
+
+  schedule:
+    - cron: 0 1 * * 1-5
 
 jobs:
   lint:
     name: Lint
-
     runs-on: ubuntu-latest
-
     steps:
-      - name: Checkout commit
-        uses: actions/checkout@v2
+      - name: Check out code
+        uses: actions/checkout@v3
 
       - name: Set up Node.js
         uses: actions/setup-node@v2
@@ -22,34 +25,73 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
-      - name: Run lints
+      - name: Lint code
         run: npm run lint
 
-  test:
-    name: Test (Node.js v${{ matrix.node-version }})
+      - name: Generate docs
+        run: npm run docs
 
+      - name: Check for uncommitted changes
+        run: |-
+          git_status=$(git status --porcelain)
+          if [[ -n "${git_status}" ]]; then
+            echo "::error::Uncommitted changes detected"
+            printf "%s\n" "${git_status}"
+            exit 1
+          fi
+
+  test-matrix:
+    name: Generate test matrix
     runs-on: ubuntu-latest
+    outputs:
+      matrix: ${{ steps.test-matrix.outputs.matrix }}
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v3
 
+      - id: test-matrix
+        name: Generate test matrix
+        run: scripts/test-matrix
+
+  test:
+    name: Test (Cerbos ${{ matrix.cerbos }} | Node ${{ matrix.node }})
+    runs-on: ubuntu-latest
+    continue-on-error: ${{ endsWith(matrix.cerbos, '-prerelease') }}
+    env:
+      CERBOS_VERSION: ${{ matrix.cerbos }}
+    needs:
+      - test-matrix
     strategy:
       fail-fast: false
-      matrix:
-        node-version:
-          - 12
-          - 14
-          - 16
-
+      matrix: ${{ fromJSON(needs.test-matrix.outputs.matrix) }}
     steps:
-      - name: Checkout commit
-        uses: actions/checkout@v2
+      - name: Check out code
+        uses: actions/checkout@v3
 
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
           cache: npm
-          node-version: ${{ matrix.node-version }}
+          node-version: ${{ matrix.node }}
+
+      - name: Update npm
+        run: npm install --global npm
 
       - name: Install dependencies
         run: npm ci
 
+      - name: Start test servers
+        run: npm run test:servers:start
+
       - name: Run tests
-        run: npm run test:with-server
+        run: npm test
+
+  test-results:
+    name: Check test results
+    runs-on: ubuntu-latest
+    if: always()
+    needs:
+      - test
+    steps:
+      - name: Check test results
+        run: test "${{ needs.test.result }}" = "success"
